Removed 'funny' characters. They add nothing to the test, but properly managing those would require filtering source files through native2ascii, then back in various IDEs on different platforms, etc, you get it...
There is still an issue with a handshake exception thrown, which wasn't there before:

javax.net.ssl.SSLException: Received close_notify during handshake

git-svn-id: file:///home/projects/mule/scm@5843 bf997673-6b11-0410-b953-e057580c5b09