Merged revisions 15992,15995-15996,16008,16013-16017,16019,16033,16036,16047,16050-16060,16067-16071,16073-16074,16094,16096 via svnmerge from https://svn.codehaus.org/mule/branches/mule-3.x
................
  r15992 | dirk.olmes | 2009-11-08 02:57:03 +0100 (Sun, 08 Nov 2009) | 2 lines
  
  fix config after merge
................
  r15995 | dirk.olmes | 2009-11-09 09:31:55 +0100 (Mon, 09 Nov 2009) | 25 lines
  
  Merged revisions 15904,15911,15914,15988-15989 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15904 | dirk.olmes | 2009-10-28 14:29:22 +0100 (Wed, 28 Oct 2009) | 1 line
    
    checkstyle
  ........
    r15911 | dirk.olmes | 2009-10-30 09:22:11 +0100 (Fri, 30 Oct 2009) | 2 lines
    
    code cleanup
  ........
    r15914 | dirk.olmes | 2009-10-30 09:47:39 +0100 (Fri, 30 Oct 2009) | 1 line
    
    MULE-4529 (Enable expression evaluation on the address property of a job-endpoint): documentation update
  ........
    r15988 | dirk.olmes | 2009-11-06 11:44:33 +0100 (Fri, 06 Nov 2009) | 1 line
    
    no System.out in tests!
  ........
    r15989 | dirk.olmes | 2009-11-06 16:39:54 +0100 (Fri, 06 Nov 2009) | 3 lines
    
    ongoing code cleanup
  ........
................
  r15996 | dirk.olmes | 2009-11-09 09:39:38 +0100 (Mon, 09 Nov 2009) | 27 lines
  
  Blocked revisions 15926,15932,15986-15987 via svnmerge
  
  ................
    r15926 | dirk.olmes | 2009-11-02 15:32:36 +0100 (Mon, 02 Nov 2009) | 9 lines
    
    Merged revisions 15925 via svnmerge from 
    https://svn.codehaus.org/mule/branches/mule-2.1.x
    
    ........
      r15925 | dirk.olmes | 2009-11-02 14:55:29 +0100 (Mon, 02 Nov 2009) | 1 line
      
      Using the most precise available timer in JDK5, tests using this class also pass on IBM's JDK.
    ........
  ................
    r15932 | dirk.olmes | 2009-11-03 02:26:08 +0100 (Tue, 03 Nov 2009) | 1 line
    
    Revert changes made in r15926, see MULE-4592 (EventGroup does not work with IBM JDK)
  ................
    r15986 | alan.cassar | 2009-11-06 10:39:24 +0100 (Fri, 06 Nov 2009) | 1 line
    
    adding mulemq version to the pom (and testing committer rights)
  ................
    r15987 | dirk.olmes | 2009-11-06 10:58:51 +0100 (Fri, 06 Nov 2009) | 2 lines
    
    rolling back r15986, tabs should really be spaces
  ................
................
  r16008 | tcarlson | 2009-11-09 17:05:46 +0100 (Mon, 09 Nov 2009) | 12 lines
  
  Blocked revisions 15155-15156 via svnmerge
  
  ........
    r15155 | tcarlson | 2009-07-06 15:17:54 -0400 (Mon, 06 Jul 2009) | 1 line
    
    Roll back part of r15132 to try to fix CI failures in 2.2.x EE
  ........
    r15156 | tcarlson | 2009-07-06 16:02:01 -0400 (Mon, 06 Jul 2009) | 1 line
    
    Revert r15155 because the 2.2.x EE build is green after all
  ........
................
  r16013 | tcarlson | 2009-11-10 00:25:40 +0100 (Tue, 10 Nov 2009) | 17 lines
  
  Merged revisions 15501-15502,15528 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15501 | tcarlson | 2009-08-24 15:32:28 -0400 (Mon, 24 Aug 2009) | 1 line
    
    Fix EE-1613
  ........
    r15502 | tcarlson | 2009-08-24 16:04:32 -0400 (Mon, 24 Aug 2009) | 1 line
    
    EE-1613 Only propagate Correlation-related properties
  ........
    r15528 | tcarlson | 2009-08-26 15:14:14 -0400 (Wed, 26 Aug 2009) | 1 line
    
    Fix EE-1611
  ........
................
  r16014 | tcarlson | 2009-11-10 00:28:18 +0100 (Tue, 10 Nov 2009) | 8 lines
  
  Blocked revisions 15529 via svnmerge
  
  ........
    r15529 | tcarlson | 2009-08-26 15:30:20 -0400 (Wed, 26 Aug 2009) | 1 line
    
    oops
  ........
................
  r16015 | tcarlson | 2009-11-10 00:34:13 +0100 (Tue, 10 Nov 2009) | 12 lines
  
  Blocked revisions 15795,15801 via svnmerge
  
  ........
    r15795 | tcarlson | 2009-10-06 21:46:21 -0400 (Tue, 06 Oct 2009) | 1 line
    
    Fix for EE-1667/EE-1275
  ........
    r15801 | aperepel | 2009-10-07 10:47:37 -0400 (Wed, 07 Oct 2009) | 1 line
    
    Reverted r15795
  ........
................
  r16016 | tcarlson | 2009-11-10 00:41:13 +0100 (Tue, 10 Nov 2009) | 8 lines
  
  Blocked revisions 15431 via svnmerge
  
  ........
    r15431 | tcarlson | 2009-08-12 11:58:17 -0400 (Wed, 12 Aug 2009) | 1 line
    
    Add new JMS test
  ........
................
  r16017 | tcarlson | 2009-11-10 01:30:34 +0100 (Tue, 10 Nov 2009) | 61 lines
  
  Merged revisions 15722 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15722 | tcarlson | 2009-09-18 16:56:41 -0400 (Fri, 18 Sep 2009) | 1 line
    
    Refactor WS-Security test cases so that the SAML module can extend them
  ........
  Merged revisions 15746 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15746 | tcarlson | 2009-09-21 13:18:02 -0400 (Mon, 21 Sep 2009) | 1 line
    
    Refactor WS-Security test cases so that the SAML module can extend them
  ........
  Merged revisions 15766 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15766 | tcarlson | 2009-09-24 10:43:14 -0400 (Thu, 24 Sep 2009) | 1 line
    
    SAAJ interceptor is not needed as of CXF 2.1.x
  ........
  Merged revisions 15767 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15767 | tcarlson | 2009-09-24 12:25:45 -0400 (Thu, 24 Sep 2009) | 1 line
    
    Update user password for tests
  ........
  Merged revisions 15768-15771,15773,15780 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15768 | tcarlson | 2009-09-24 12:26:34 -0400 (Thu, 24 Sep 2009) | 1 line
    
    Add a test case for CertificateToken profile
  ........
    r15769 | tcarlson | 2009-09-24 13:40:07 -0400 (Thu, 24 Sep 2009) | 1 line
    
    Simpler config
  ........
    r15770 | tcarlson | 2009-09-24 13:40:40 -0400 (Thu, 24 Sep 2009) | 1 line
    
    Add a test case for WSS encryption
  ........
    r15771 | tcarlson | 2009-09-25 10:56:05 -0400 (Fri, 25 Sep 2009) | 1 line
    
    BouncyCastle needs to be provided since it's JDK-specific
  ........
    r15773 | tcarlson | 2009-09-27 09:28:57 -0400 (Sun, 27 Sep 2009) | 1 line
    
    Bump WSS4J to the latest version
  ........
    r15780 | tcarlson | 2009-09-29 09:12:08 -0400 (Tue, 29 Sep 2009) | 1 line
    
    Bubble up security exceptions from web service calls
  ........
................
  r16019 | dirk.olmes | 2009-11-10 03:52:06 +0100 (Tue, 10 Nov 2009) | 2 lines
  
  update config to 3.x, add generics
................
  r16033 | dfeist | 2009-11-11 13:51:51 +0100 (Wed, 11 Nov 2009) | 33 lines
  
  Merged revisions 15965,16009,16011,16018,16021,16023-16024 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r15965 | dfeist | 2009-11-04 12:30:58 -0200 (Wed, 04 Nov 2009) | 1 line
    
    MULE-4594 Implement a ServletContextListener that configures an existing Mule instance rather than starting a new instance
  ........
    r16009 | dfeist | 2009-11-09 15:12:59 -0200 (Mon, 09 Nov 2009) | 1 line
    
    MULE-4572 Connector thread pools should not be created with the current threads contextClassloader
  ........
    r16011 | dfeist | 2009-11-09 17:32:36 -0200 (Mon, 09 Nov 2009) | 1 line
    
    MULE-4579 CXF transport does not dispose receivers correctly/fully when a listener is unregistered.
  ........
    r16018 | dfeist | 2009-11-10 00:22:03 -0200 (Tue, 10 Nov 2009) | 1 line
    
    MULE-4490 Committing test case that reproduces issue (Outbound CXF endpoint does not propagate any properties to "protocol" endpoint)
  ........
    r16021 | dfeist | 2009-11-10 10:32:41 -0200 (Tue, 10 Nov 2009) | 1 line
    
    MULE-4605 Unable to use multiple spring registries as default mule config and required editors/processors are defined in same file.
  ........
    r16023 | dfeist | 2009-11-10 11:12:17 -0200 (Tue, 10 Nov 2009) | 1 line
    
    MULE-4490 Outbound CXF endpoint does not propagate any properties to "protocol" endpoint
  ........
    r16024 | dfeist | 2009-11-10 11:53:37 -0200 (Tue, 10 Nov 2009) | 1 line
    
    MULE-4490 Outbound CXF endpoint does not propagate any properties to "protocol" endpoint
  ........
................
  r16036 | rossmason | 2009-11-11 19:32:25 +0100 (Wed, 11 Nov 2009) | 1 line
  
  added a couple of helper methods
................
  r16047 | rossmason | 2009-11-13 22:40:48 +0100 (Fri, 13 Nov 2009) | 1 line
  
  Added support for simple factories for bootstrapping.  cleaned up the code a bit
................
  r16050 | rossmason | 2009-11-14 12:51:52 +0100 (Sat, 14 Nov 2009) | 1 line
  
  bad checkin.  must review before commit....
................
  r16051 | rossmason | 2009-11-15 00:33:37 +0100 (Sun, 15 Nov 2009) | 1 line
  
  MULE-4609. We're now using Jackson!
................
  r16052 | rossmason | 2009-11-15 00:34:01 +0100 (Sun, 15 Nov 2009) | 1 line
  
  add support for getting the object name from an attribute
................
  r16053 | rossmason | 2009-11-15 00:57:21 +0100 (Sun, 15 Nov 2009) | 1 line
  
  MULE-4609. We're now using Jackson!
................
  r16054 | rossmason | 2009-11-15 19:05:42 +0100 (Sun, 15 Nov 2009) | 1 line
  
  Fixed flawed logic in the isJson filter
................
  r16055 | rossmason | 2009-11-15 20:03:51 +0100 (Sun, 15 Nov 2009) | 1 line
  
  Jackson more strict about quotes
................
  r16056 | rossmason | 2009-11-15 20:04:09 +0100 (Sun, 15 Nov 2009) | 1 line
  
  we should use Jackson directly here
................
  r16057 | rossmason | 2009-11-15 21:38:51 +0100 (Sun, 15 Nov 2009) | 1 line
  
  update the build/whitelists
................
  r16058 | rossmason | 2009-11-15 23:53:32 +0100 (Sun, 15 Nov 2009) | 1 line
  
  added some javadoc
................
  r16059 | rossmason | 2009-11-15 23:54:16 +0100 (Sun, 15 Nov 2009) | 1 line
  
  use correct payload
................
  r16060 | rossmason | 2009-11-16 00:06:15 +0100 (Mon, 16 Nov 2009) | 1 line
  
  added test and doc for quoted strings
................
  r16067 | tcarlson | 2009-11-16 22:47:26 +0100 (Mon, 16 Nov 2009) | 13 lines
  
  Merged revisions 16061,16064 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16061 | tcarlson | 2009-11-16 11:27:00 -0300 (Mon, 16 Nov 2009) | 1 line
    
    Work around the race condition in EE-1275
  ........
    r16064 | tcarlson | 2009-11-16 12:53:30 -0300 (Mon, 16 Nov 2009) | 1 line
    
    Revert r16061 and hopefully fix EE-1275 for good
  ........
................
  r16068 | dirk.olmes | 2009-11-17 10:46:11 +0100 (Tue, 17 Nov 2009) | 9 lines
  
  Merged revisions 16031 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16031 | dirk.olmes | 2009-11-11 11:06:46 +0100 (Wed, 11 Nov 2009) | 1 line
    
    Use jaxp to retrieve a valid XPathFactory. This works on Sun JDK as well as on IBM JDK.
  ........
................
  r16069 | dirk.olmes | 2009-11-17 10:59:38 +0100 (Tue, 17 Nov 2009) | 9 lines
  
  Merged revisions 16045 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16045 | dirk.olmes | 2009-11-13 15:03:16 +0100 (Fri, 13 Nov 2009) | 2 lines
    
    MULE-4607 (Installing Mule as Windows service throws NoClassDefFoundError)
  ........
................
  r16070 | rossmason | 2009-11-17 13:58:59 +0100 (Tue, 17 Nov 2009) | 1 line
  
  MULE-4611.  Broke out Transform resolver functionality into its own API
................
  r16071 | rossmason | 2009-11-17 13:59:23 +0100 (Tue, 17 Nov 2009) | 1 line
  
  Added some more annotation discovery methods
................
  r16073 | rossmason | 2009-11-18 10:54:24 +0100 (Wed, 18 Nov 2009) | 1 line
  
  made this transformer optional since it requires a runtime dependency on the servlet API. If a project doesn't have the API on the classpath, it will not need this transformer
................
  r16074 | rossmason | 2009-11-19 12:22:54 +0100 (Thu, 19 Nov 2009) | 1 line
  
  Always select the TypeBasedTransformer resolver last
................
  r16094 | tcarlson | 2009-11-21 00:34:47 +0100 (Sat, 21 Nov 2009) | 9 lines
  
  Merged revisions 16093 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16093 | tcarlson | 2009-11-20 20:28:40 -0300 (Fri, 20 Nov 2009) | 1 line
    
    Fix EE-1734
  ........
................
  r16096 | dirk.olmes | 2009-11-23 10:36:14 +0100 (Mon, 23 Nov 2009) | 1 line
  
  fix the build for 3.x
................


git-svn-id: file:///home/projects/mule/scm@16100 bf997673-6b11-0410-b953-e057580c5b09