Merged revisions 16047,16050-16060,16067-16071 via svnmerge from https://svn.codehaus.org/mule/branches/mule-3.x
................
  r16047 | rossmason | 2009-11-13 22:40:48 +0100 (Fri, 13 Nov 2009) | 1 line
  
  Added support for simple factories for bootstrapping.  cleaned up the code a bit
................
  r16050 | rossmason | 2009-11-14 12:51:52 +0100 (Sat, 14 Nov 2009) | 1 line
  
  bad checkin.  must review before commit....
................
  r16051 | rossmason | 2009-11-15 00:33:37 +0100 (Sun, 15 Nov 2009) | 1 line
  
  MULE-4609. We're now using Jackson!
................
  r16052 | rossmason | 2009-11-15 00:34:01 +0100 (Sun, 15 Nov 2009) | 1 line
  
  add support for getting the object name from an attribute
................
  r16053 | rossmason | 2009-11-15 00:57:21 +0100 (Sun, 15 Nov 2009) | 1 line
  
  MULE-4609. We're now using Jackson!
................
  r16054 | rossmason | 2009-11-15 19:05:42 +0100 (Sun, 15 Nov 2009) | 1 line
  
  Fixed flawed logic in the isJson filter
................
  r16055 | rossmason | 2009-11-15 20:03:51 +0100 (Sun, 15 Nov 2009) | 1 line
  
  Jackson more strict about quotes
................
  r16056 | rossmason | 2009-11-15 20:04:09 +0100 (Sun, 15 Nov 2009) | 1 line
  
  we should use Jackson directly here
................
  r16057 | rossmason | 2009-11-15 21:38:51 +0100 (Sun, 15 Nov 2009) | 1 line
  
  update the build/whitelists
................
  r16058 | rossmason | 2009-11-15 23:53:32 +0100 (Sun, 15 Nov 2009) | 1 line
  
  added some javadoc
................
  r16059 | rossmason | 2009-11-15 23:54:16 +0100 (Sun, 15 Nov 2009) | 1 line
  
  use correct payload
................
  r16060 | rossmason | 2009-11-16 00:06:15 +0100 (Mon, 16 Nov 2009) | 1 line
  
  added test and doc for quoted strings
................
  r16067 | tcarlson | 2009-11-16 22:47:26 +0100 (Mon, 16 Nov 2009) | 13 lines
  
  Merged revisions 16061,16064 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16061 | tcarlson | 2009-11-16 11:27:00 -0300 (Mon, 16 Nov 2009) | 1 line
    
    Work around the race condition in EE-1275
  ........
    r16064 | tcarlson | 2009-11-16 12:53:30 -0300 (Mon, 16 Nov 2009) | 1 line
    
    Revert r16061 and hopefully fix EE-1275 for good
  ........
................
  r16068 | dirk.olmes | 2009-11-17 10:46:11 +0100 (Tue, 17 Nov 2009) | 9 lines
  
  Merged revisions 16031 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16031 | dirk.olmes | 2009-11-11 11:06:46 +0100 (Wed, 11 Nov 2009) | 1 line
    
    Use jaxp to retrieve a valid XPathFactory. This works on Sun JDK as well as on IBM JDK.
  ........
................
  r16069 | dirk.olmes | 2009-11-17 10:59:38 +0100 (Tue, 17 Nov 2009) | 9 lines
  
  Merged revisions 16045 via svnmerge from 
  https://svn.codehaus.org/mule/branches/mule-2.2.x
  
  ........
    r16045 | dirk.olmes | 2009-11-13 15:03:16 +0100 (Fri, 13 Nov 2009) | 2 lines
    
    MULE-4607 (Installing Mule as Windows service throws NoClassDefFoundError)
  ........
................
  r16070 | rossmason | 2009-11-17 13:58:59 +0100 (Tue, 17 Nov 2009) | 1 line
  
  MULE-4611.  Broke out Transform resolver functionality into its own API
................
  r16071 | rossmason | 2009-11-17 13:59:23 +0100 (Tue, 17 Nov 2009) | 1 line
  
  Added some more annotation discovery methods
................


git-svn-id: file:///home/projects/mule/scm@16072 bf997673-6b11-0410-b953-e057580c5b09